apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  generateName: tekton-kn-sample-
spec:
  serviceAccountName: pipeline-account
  pipelineRef:
    name: build-and-deploy-pipeline
  resources:
    - name: git-source
      resourceRef:
        name: tekton-knative-git
  params:
    - name: pathToContext
      value: "src"
    - name: pathToYamlFile
      value: "knative/get_shop_info.yaml"
    - name: imageUrl
      value: "kangkangkid/websocketorder"
    - name: imageTag
      value: "latest"
  ServiceAccount: pipeline-account