apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: get-shop-info
  namespace: default
spec:
  template:
    metadata:
      labels:
        app: websocketorder
      annotations:
        autoscaling.knative.dev/target: "10"
    spec:
      containers:
        - image: __IMAGE__