apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: source-to-image-bill
spec:
  inputs:
    resources:
      - name: repo
        type: git
    params:
      - name: pathToContext
        description: The path to the build context, used by Kaniko - within the workspace
        default: .
      - name: pathToDockerFile
        description: The path to the dockerfile to build (relative to the context)
        default: Dockerfile
      - name: imageUrl
        description: Url of image repository
      - name: imageTag
        description: Tag to apply to the built image
        default: "2.0"
  steps:
    - name: build-and-push-bill
      image: kangkangkid/kaniko-executor:v0.22.0
      env:
      - name: DOCKER_CONFIG
        value: /tekton/home/.docker
      command:
        - /kaniko/executor

        - --dockerfile=Dockerfile
        - --context=/workspace/repo/bill/src
        - --destination=kangkangkid/bill:2.0

